title: Azure Network Security Workshop
description: Hands-on workshop for Azure network security controls and simulations
remote_theme: just-the-docs/just-the-docs
url: "https://benyibrani.github.io"
baseurl: "/network-security-workshop"

# Just the Docs settings
color_scheme: light
search_enabled: true
heading_anchors: true

aux_links:
  "Workshop Repository":
    - "https://github.com/benyibrani/network-security-workshop"

nav_sort: case_insensitive

plugins:
  - jekyll-remote-theme

# Build settings
markdown: kramdown
permalink: pretty
